import { Game } from "../Types/gameType";

export const NAMES_PROP = {
    imgUrl: "",
    name: "Назва",
    platform: "Платформа",
    localizetion: "Локалізатор",
    discType: "Тип носія",
    genre: "Жанр",
    box: "Коробка",
    developer: "Розробник",
    pg: "Вік від",
    publisher: "Видавець",
    features: "Особливості",
    developCountry: "Країна розробник",
    brendFrom: "Країна видавець",
    release: "Дата релізу",
    releaseUkr: "Дата релізу в Україні",
    systemRequirements: "Системні вимоги ",
    playersNum: "Кількість гравців",
    Guarantee: "Гарантія",
    servicActiv: "",
    minRequireSis: "Мінімальні системні вимоги",
    distributorInUkraine: "Дистрибютор в Україні",
    _id: "Унікальний ID товара ",
    price: "Ціна",
};
